# Generated by Django 4.1.1 on 2022-09-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), unique=True),
        ),
    ]
