# Generated by Django 4.1.1 on 2022-09-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_venue_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together=set(),
        ),
    ]
