# Generated by Django 4.1.1 on 2022-09-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_venue_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.IntegerField(verbose_name='How much is the ticket?'),
        ),
    ]
